### ISSUE TITLE
Action preconditions failing cause main module to exit and start new evaluation round

### ISSUE THREAD

**Issue by jzvandenoever** [goalhub/runtime#8]
When performing an action in the main module and the precondition fails the agent does not evaluate the subsequent rules in the module. This can cause an agent to get into a loop of continuously failing the same action on the preconditions.

This was done using the default order.

**Comment by Venorcis** [comment]
Hey Joris,

Which version of GOAL (in Eclipse?) are you using? And what kind of agent?
I just tried to reproduce this issue, and was unsuccesful. For example, this main module:
```
use counter as knowledge.
use script as beliefs.
use printText as actionspec.
exit=nogoals.

module printScript {
	if true then failingAction.
	if goal( nrOfPrintedLines(_) ), bel( nrOfPrintedLines(LineNr), NextLine is LineNr+1, script(NextLine, Text) )
		then printText(Text).
}
```
with this actionspec
```
use dummy as knowledge.

% The action printText expects a string of the form "..." as its argument. 
% It can always be performed and has no other effect than printing Text to a window.
define printText(Text) with
	pre{ true }
	post{ true }
	
define failingAction with
	pre{ not(true) }
	post{ true }
```
works just fine in the latest development version (which we'll be releasing to master this week actually).

**Comment by Venorcis** [comment]
Cannot reproduce in latest GOAL version(s)
